#!/usr/bin/env node
// Regenerate every `<engine>/01_samples.*` seed in this repo.
//
//   node generator/generate.mjs
//   SCALE=0.1 node generator/generate.mjs   # bigger, if you want it
//
// The seeds are committed rather than generated at run time on purpose: an
// engine's container init hook loads them on first boot, so `compose up` gives a
// populated database with no extra step. That only works if the file is already
// there, which is also why the default scale is small — these are meant to be
// readable and to boot in seconds, not to be a benchmark. The irodori-table
// database playground is where the 196k-row version lives.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import { build, meta, N } from './core.mjs'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const data = build()

const write = (rel, body) => {
  const path = join(ROOT, rel)
  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, body.endsWith('\n') ? body : body + '\n')
  const lines = body.trim().split('\n').length
  console.log(`  ${rel.padEnd(34)} ${String(lines).padStart(6)} lines`)
}

// --- literal helpers --------------------------------------------------------
const sq = (v) => (v === null || v === undefined ? 'NULL' : `'${String(v).replaceAll("'", "''")}'`)
const num = (v) => (v === null || v === undefined ? 'NULL' : String(v))
const bool = (v, style = 'sql') =>
  style === 'int' ? (v ? '1' : '0') : v ? 'TRUE' : 'FALSE'
const json = (v) => sq(JSON.stringify(v))

// INSERT statements in batches, so a seed file stays diffable and no single
// statement grows past what an engine will parse.
const inserts = (table, columns, rows, toValues, batch = 100) => {
  const out = []
  for (let i = 0; i < rows.length; i += batch) {
    const chunk = rows.slice(i, i + batch)
    out.push(
      `INSERT INTO ${table} (${columns.join(', ')}) VALUES\n` +
        chunk.map((r) => '  (' + toValues(r).join(', ') + ')').join(',\n') +
        ';',
    )
  }
  return out.join('\n')
}

const banner = (engine) =>
  `-- Irodori Table sample data — ${engine}.\n` +
  `-- Generated by generator/generate.mjs (seed=${meta.SEED}, scale=${meta.SCALE}).\n` +
  `-- Do not edit by hand; re-run the generator instead.\n` +
  `-- ${N.customers} customers, ${N.products} products, ${data.orders.length} orders, ` +
  `${data.orderItems.length} order lines, ${data.events.length} events.\n`

console.log(`seed=${meta.SEED} scale=${meta.SCALE}`)

// --- PostgreSQL wire --------------------------------------------------------
// Also loaded into TimescaleDB, CockroachDB and YugabyteDB, so it stays on the
// common subset: no GIN index, no stored generated column.
{
  const s = [banner('PostgreSQL (also TimescaleDB, CockroachDB, YugabyteDB)')]
  s.push(`
DROP VIEW  IF EXISTS top_products;
DROP VIEW  IF EXISTS customer_lifetime_value;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS customers;
DROP TYPE  IF EXISTS order_status;
DROP TYPE  IF EXISTS customer_tier;

CREATE TYPE customer_tier AS ENUM ('bronze', 'silver', 'gold', 'platinum');
CREATE TYPE order_status  AS ENUM ('pending', 'processing', 'shipped', 'delivered', 'cancelled', 'refunded');

CREATE TABLE customers (
  id            integer        PRIMARY KEY,
  name          text           NOT NULL,
  email         text           NOT NULL UNIQUE,
  country_code  char(2)        NOT NULL,
  tier          customer_tier  NOT NULL,
  credit_limit  numeric(14, 2) NOT NULL CHECK (credit_limit >= 0),
  is_active     boolean        NOT NULL,
  signup_source text           NOT NULL,
  created_at    timestamptz    NOT NULL,
  metadata      jsonb          NOT NULL
);

CREATE TABLE products (
  id          integer        PRIMARY KEY,
  sku         text           NOT NULL UNIQUE,
  name        text           NOT NULL,
  category    text           NOT NULL,
  price       numeric(12, 2) NOT NULL CHECK (price >= 0),
  weight_kg   numeric(8, 3)  NOT NULL,
  in_stock    boolean        NOT NULL,
  supplier    text           NOT NULL,
  released_on date           NOT NULL,
  tags        jsonb          NOT NULL
);

CREATE TABLE orders (
  id          integer        PRIMARY KEY,
  customer_id integer        NOT NULL REFERENCES customers (id),
  status      order_status   NOT NULL,
  channel     text           NOT NULL,
  currency    char(3)        NOT NULL,
  subtotal    numeric(14, 2) NOT NULL,
  tax         numeric(14, 2) NOT NULL,
  total       numeric(14, 2) NOT NULL,
  ordered_at  timestamptz    NOT NULL,
  shipped_at  timestamptz,
  note        text,
  CONSTRAINT orders_ship_after_order CHECK (shipped_at IS NULL OR shipped_at >= ordered_at)
);

CREATE TABLE order_items (
  id            integer        PRIMARY KEY,
  order_id      integer        NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
  product_id    integer        NOT NULL REFERENCES products (id),
  quantity      integer        NOT NULL CHECK (quantity > 0),
  unit_price    numeric(12, 2) NOT NULL,
  discount_rate numeric(4, 2)  NOT NULL,
  line_total    numeric(14, 2) NOT NULL
);

CREATE TABLE events (
  id          integer     PRIMARY KEY,
  customer_id integer     NOT NULL REFERENCES customers (id),
  event_type  text        NOT NULL,
  occurred_at timestamptz NOT NULL,
  session_id  text        NOT NULL,
  device      text        NOT NULL,
  duration_ms integer     NOT NULL,
  payload     jsonb       NOT NULL
);

CREATE INDEX idx_customers_tier    ON customers (tier);
CREATE INDEX idx_orders_customer   ON orders (customer_id);
CREATE INDEX idx_orders_ordered_at ON orders (ordered_at DESC);
CREATE INDEX idx_items_order       ON order_items (order_id);
CREATE INDEX idx_events_customer   ON events (customer_id, occurred_at DESC);

COMMENT ON TABLE  customers          IS 'Registered buyers. One row per account.';
COMMENT ON COLUMN orders.shipped_at  IS 'NULL until the order ships.';
COMMENT ON TABLE  order_items        IS 'Order lines. subtotal on the order is their exact sum.';
`)
  s.push(inserts('customers',
    ['id', 'name', 'email', 'country_code', 'tier', 'credit_limit', 'is_active', 'signup_source', 'created_at', 'metadata'],
    data.customers,
    (c) => [num(c.id), sq(c.name), sq(c.email), sq(c.country_code), sq(c.tier),
      num(c.credit_limit), bool(c.is_active), sq(c.signup_source), sq(c.created_at), json(c.metadata)]))
  s.push(inserts('products',
    ['id', 'sku', 'name', 'category', 'price', 'weight_kg', 'in_stock', 'supplier', 'released_on', 'tags'],
    data.products,
    (p) => [num(p.id), sq(p.sku), sq(p.name), sq(p.category), num(p.price), num(p.weight_kg),
      bool(p.in_stock), sq(p.supplier), sq(p.released_on), json(p.tags)]))
  s.push(inserts('orders',
    ['id', 'customer_id', 'status', 'channel', 'currency', 'subtotal', 'tax', 'total', 'ordered_at', 'shipped_at', 'note'],
    data.orders,
    (o) => [num(o.id), num(o.customer_id), sq(o.status), sq(o.channel), sq(o.currency),
      num(o.subtotal), num(o.tax), num(o.total), sq(o.ordered_at), sq(o.shipped_at), sq(o.note)]))
  s.push(inserts('order_items',
    ['id', 'order_id', 'product_id', 'quantity', 'unit_price', 'discount_rate', 'line_total'],
    data.orderItems,
    (i) => [num(i.id), num(i.order_id), num(i.product_id), num(i.quantity),
      num(i.unit_price), num(i.discount_rate), num(i.line_total)]))
  s.push(inserts('events',
    ['id', 'customer_id', 'event_type', 'occurred_at', 'session_id', 'device', 'duration_ms', 'payload'],
    data.events,
    (e) => [num(e.id), num(e.customer_id), sq(e.event_type), sq(e.occurred_at), sq(e.session_id),
      sq(e.device), num(e.duration_ms), json(e.payload)]))
  s.push(`
CREATE VIEW customer_lifetime_value AS
  SELECT c.id AS customer_id, c.name, c.country_code, c.tier,
         count(o.id)                         AS order_count,
         coalesce(sum(o.total), 0)           AS lifetime_value,
         max(o.ordered_at)                   AS last_order_at
  FROM customers c
  LEFT JOIN orders o ON o.customer_id = c.id AND o.status <> 'cancelled'
  GROUP BY c.id, c.name, c.country_code, c.tier;

CREATE VIEW top_products AS
  SELECT p.id, p.sku, p.name, p.category,
         sum(i.quantity) AS units_sold, sum(i.line_total) AS revenue
  FROM products p
  JOIN order_items i ON i.product_id = p.id
  GROUP BY p.id, p.sku, p.name, p.category;

ANALYZE;
`)
  // A second, unrelated object graph: countries -> producers -> cheeses ->
  // reviews. It exists for FK navigation and structure browsing, which the flat
  // e-commerce tables do not exercise, and irodori-table's integration test
  // asserts on it by name. Static, so it is read rather than generated.
  s.push(readFileSync(join(ROOT, 'generator/postgres-demo.sql'), 'utf8'))
  write('postgres/01_samples.sql', s.join('\n'))
}

// --- MySQL wire -------------------------------------------------------------
// Also loaded into MariaDB and TiDB.
{
  const s = [banner('MySQL (also MariaDB, TiDB)')]
  s.push(`
-- The entrypoint pipes this file through the mysql client on a connection whose
-- default charset is latin1, so without this every multi-byte name is stored
-- double-encoded: char_length('佐藤 彩') comes back as 10 and not 4.
SET NAMES utf8mb4;

SET FOREIGN_KEY_CHECKS = 0;
DROP VIEW  IF EXISTS top_products;
DROP VIEW  IF EXISTS customer_lifetime_value;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS customers;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE customers (
  id            INT            NOT NULL PRIMARY KEY,
  name          VARCHAR(200)   NOT NULL,
  email         VARCHAR(200)   NOT NULL UNIQUE,
  country_code  CHAR(2)        NOT NULL,
  tier          ENUM('bronze','silver','gold','platinum') NOT NULL,
  credit_limit  DECIMAL(14,2)  NOT NULL,
  is_active     BOOLEAN        NOT NULL,
  signup_source VARCHAR(40)    NOT NULL,
  created_at    DATETIME       NOT NULL,
  metadata      JSON           NOT NULL,
  KEY idx_customers_tier (tier)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Registered buyers.';

CREATE TABLE products (
  id          INT           NOT NULL PRIMARY KEY,
  sku         VARCHAR(32)   NOT NULL UNIQUE,
  name        VARCHAR(200)  NOT NULL,
  category    VARCHAR(60)   NOT NULL,
  price       DECIMAL(12,2) NOT NULL,
  weight_kg   DECIMAL(8,3)  NOT NULL,
  in_stock    BOOLEAN       NOT NULL,
  supplier    VARCHAR(120)  NOT NULL,
  released_on DATE          NOT NULL,
  tags        JSON          NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE orders (
  id          INT           NOT NULL PRIMARY KEY,
  customer_id INT           NOT NULL,
  status      ENUM('pending','processing','shipped','delivered','cancelled','refunded') NOT NULL,
  channel     VARCHAR(40)   NOT NULL,
  currency    CHAR(3)       NOT NULL,
  subtotal    DECIMAL(14,2) NOT NULL,
  tax         DECIMAL(14,2) NOT NULL,
  total       DECIMAL(14,2) NOT NULL,
  ordered_at  DATETIME      NOT NULL,
  shipped_at  DATETIME      NULL COMMENT 'NULL until the order ships.',
  note        VARCHAR(200)  NULL,
  KEY idx_orders_customer (customer_id),
  KEY idx_orders_ordered_at (ordered_at),
  CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES customers (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE order_items (
  id            INT           NOT NULL PRIMARY KEY,
  order_id      INT           NOT NULL,
  product_id    INT           NOT NULL,
  quantity      INT           NOT NULL,
  unit_price    DECIMAL(12,2) NOT NULL,
  discount_rate DECIMAL(4,2)  NOT NULL,
  line_total    DECIMAL(14,2) NOT NULL,
  gross_amount  DECIMAL(16,2) AS (unit_price * quantity) STORED,
  KEY idx_items_order (order_id),
  CONSTRAINT fk_items_order   FOREIGN KEY (order_id)   REFERENCES orders (id) ON DELETE CASCADE,
  CONSTRAINT fk_items_product FOREIGN KEY (product_id) REFERENCES products (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE events (
  id          INT          NOT NULL PRIMARY KEY,
  customer_id INT          NOT NULL,
  event_type  VARCHAR(40)  NOT NULL,
  occurred_at DATETIME     NOT NULL,
  session_id  VARCHAR(40)  NOT NULL,
  device      VARCHAR(40)  NOT NULL,
  duration_ms INT          NOT NULL,
  payload     JSON         NOT NULL,
  KEY idx_events_customer (customer_id, occurred_at),
  CONSTRAINT fk_events_customer FOREIGN KEY (customer_id) REFERENCES customers (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
`)
  s.push(inserts('customers',
    ['id', 'name', 'email', 'country_code', 'tier', 'credit_limit', 'is_active', 'signup_source', 'created_at', 'metadata'],
    data.customers,
    (c) => [num(c.id), sq(c.name), sq(c.email), sq(c.country_code), sq(c.tier),
      num(c.credit_limit), bool(c.is_active, 'int'), sq(c.signup_source), sq(c.created_at), json(c.metadata)]))
  s.push(inserts('products',
    ['id', 'sku', 'name', 'category', 'price', 'weight_kg', 'in_stock', 'supplier', 'released_on', 'tags'],
    data.products,
    (p) => [num(p.id), sq(p.sku), sq(p.name), sq(p.category), num(p.price), num(p.weight_kg),
      bool(p.in_stock, 'int'), sq(p.supplier), sq(p.released_on), json(p.tags)]))
  s.push(inserts('orders',
    ['id', 'customer_id', 'status', 'channel', 'currency', 'subtotal', 'tax', 'total', 'ordered_at', 'shipped_at', 'note'],
    data.orders,
    (o) => [num(o.id), num(o.customer_id), sq(o.status), sq(o.channel), sq(o.currency),
      num(o.subtotal), num(o.tax), num(o.total), sq(o.ordered_at), sq(o.shipped_at), sq(o.note)]))
  s.push(inserts('order_items',
    ['id', 'order_id', 'product_id', 'quantity', 'unit_price', 'discount_rate', 'line_total'],
    data.orderItems,
    (i) => [num(i.id), num(i.order_id), num(i.product_id), num(i.quantity),
      num(i.unit_price), num(i.discount_rate), num(i.line_total)]))
  s.push(inserts('events',
    ['id', 'customer_id', 'event_type', 'occurred_at', 'session_id', 'device', 'duration_ms', 'payload'],
    data.events,
    (e) => [num(e.id), num(e.customer_id), sq(e.event_type), sq(e.occurred_at), sq(e.session_id),
      sq(e.device), num(e.duration_ms), json(e.payload)]))
  s.push(`
CREATE VIEW customer_lifetime_value AS
  SELECT c.id AS customer_id, c.name, c.country_code, c.tier,
         COUNT(o.id) AS order_count, COALESCE(SUM(o.total), 0) AS lifetime_value,
         MAX(o.ordered_at) AS last_order_at
  FROM customers c
  LEFT JOIN orders o ON o.customer_id = c.id AND o.status <> 'cancelled'
  GROUP BY c.id, c.name, c.country_code, c.tier;

CREATE VIEW top_products AS
  SELECT p.id, p.sku, p.name, p.category,
         SUM(i.quantity) AS units_sold, SUM(i.line_total) AS revenue
  FROM products p
  JOIN order_items i ON i.product_id = p.id
  GROUP BY p.id, p.sku, p.name, p.category;
`)
  write('mysql/01_samples.sql', s.join('\n'))
}

// --- MongoDB ----------------------------------------------------------------
// order_items are embedded in their order, which is the document shape; the
// lines are all still there, inside the arrays.
{
  const iso = (msValue) => `ISODate("${new Date(Math.floor(msValue / 1000) * 1000).toISOString()}")`
  const s = [
    `// Irodori Table sample data — MongoDB.`,
    `// Generated by generator/generate.mjs (seed=${meta.SEED}, scale=${meta.SCALE}).`,
    `// Do not edit by hand; re-run the generator instead.`,
    `//`,
    `// order_items are embedded in orders, so this is ${data.orders.length} order`,
    `// documents holding ${data.orderItems.length} lines between them.`,
    `const db = db.getSiblingDB("samples");`,
    `db.customers.drop(); db.products.drop(); db.orders.drop(); db.events.drop();`,
  ]
  const many = (coll, rows, toDoc) => {
    const out = []
    for (let i = 0; i < rows.length; i += 100) {
      out.push(`db.${coll}.insertMany([\n` +
        rows.slice(i, i + 100).map((r) => '  ' + toDoc(r)).join(',\n') + '\n]);')
    }
    return out.join('\n')
  }
  s.push(many('customers', data.customers, (c) => JSON.stringify({
    _id: c.id, name: c.name, email: c.email, country_code: c.country_code, tier: c.tier,
    credit_limit: c.credit_limit, is_active: c.is_active, signup_source: c.signup_source,
    metadata: c.metadata,
  }).replace(/}$/, `,"created_at":${iso(c.created_ms)}}`)))
  s.push(many('products', data.products, (p) => JSON.stringify({
    _id: p.id, sku: p.sku, name: p.name, category: p.category, price: p.price,
    weight_kg: p.weight_kg, in_stock: p.in_stock, supplier: p.supplier,
    released_on: p.released_on, tags: p.tags,
  })))
  s.push(many('orders', data.orders, (o) => {
    const doc = JSON.stringify({
      _id: o.id, customer_id: o.customer_id, status: o.status, channel: o.channel,
      currency: o.currency, subtotal: o.subtotal, tax: o.tax, total: o.total,
      note: o.note,
      items: o.items.map((i) => ({
        product_id: i.product_id, quantity: i.quantity, unit_price: i.unit_price,
        discount_rate: i.discount_rate, line_total: i.line_total,
      })),
    })
    const shipped = o.shipped_at
      ? `ISODate("${o.shipped_at.replace(' ', 'T')}.000Z")`
      : 'null'
    return doc.replace(/}$/, `,"ordered_at":${iso(o.ordered_ms)},"shipped_at":${shipped}}`)
  }))
  s.push(many('events', data.events, (e) => JSON.stringify({
    _id: e.id, customer_id: e.customer_id, event_type: e.event_type,
    session_id: e.session_id, device: e.device, duration_ms: e.duration_ms,
    payload: e.payload,
  }).replace(/}$/, `,"occurred_at":${iso(e.occurred_ms)}}`)))
  s.push(`
db.customers.createIndex({ country_code: 1 });
db.customers.createIndex({ tier: 1, credit_limit: -1 });
db.products.createIndex({ sku: 1 }, { unique: true });
db.orders.createIndex({ customer_id: 1, ordered_at: -1 });
db.orders.createIndex({ "items.product_id": 1 });
db.events.createIndex({ customer_id: 1, occurred_at: -1 });
`)
  write('mongodb/01_samples.js', s.join('\n'))
}

// --- Oracle -----------------------------------------------------------------
{
  const s = [banner('Oracle Database Free')]
  s.push(`
WHENEVER SQLERROR CONTINUE;
DROP TABLE events CASCADE CONSTRAINTS PURGE;
DROP TABLE order_items CASCADE CONSTRAINTS PURGE;
DROP TABLE orders CASCADE CONSTRAINTS PURGE;
DROP TABLE products CASCADE CONSTRAINTS PURGE;
DROP TABLE customers CASCADE CONSTRAINTS PURGE;
WHENEVER SQLERROR EXIT SQL.SQLCODE;

CREATE TABLE customers (
  id            NUMBER(10)     PRIMARY KEY,
  name          VARCHAR2(200)  NOT NULL,
  email         VARCHAR2(200)  NOT NULL UNIQUE,
  country_code  CHAR(2)        NOT NULL,
  tier          VARCHAR2(10)   NOT NULL,
  credit_limit  NUMBER(14,2)   NOT NULL,
  is_active     NUMBER(1)      NOT NULL,
  signup_source VARCHAR2(40)   NOT NULL,
  created_at    TIMESTAMP      NOT NULL,
  metadata      VARCHAR2(4000) NOT NULL,
  CONSTRAINT ck_customers_meta CHECK (metadata IS JSON)
);

CREATE TABLE products (
  id          NUMBER(10)    PRIMARY KEY,
  sku         VARCHAR2(32)  NOT NULL UNIQUE,
  name        VARCHAR2(200) NOT NULL,
  category    VARCHAR2(60)  NOT NULL,
  price       NUMBER(12,2)  NOT NULL,
  weight_kg   NUMBER(8,3)   NOT NULL,
  in_stock    NUMBER(1)     NOT NULL,
  supplier    VARCHAR2(120) NOT NULL,
  released_on DATE          NOT NULL,
  tags        VARCHAR2(400) NOT NULL
);

CREATE TABLE orders (
  id          NUMBER(10)    PRIMARY KEY,
  customer_id NUMBER(10)    NOT NULL REFERENCES customers (id),
  status      VARCHAR2(12)  NOT NULL,
  channel     VARCHAR2(20)  NOT NULL,
  currency    CHAR(3)       NOT NULL,
  subtotal    NUMBER(14,2)  NOT NULL,
  tax         NUMBER(14,2)  NOT NULL,
  total       NUMBER(14,2)  NOT NULL,
  ordered_at  TIMESTAMP     NOT NULL,
  shipped_at  TIMESTAMP,
  note        VARCHAR2(200)
);

CREATE TABLE order_items (
  id            NUMBER(10)   PRIMARY KEY,
  order_id      NUMBER(10)   NOT NULL REFERENCES orders (id),
  product_id    NUMBER(10)   NOT NULL REFERENCES products (id),
  quantity      NUMBER(6)    NOT NULL,
  unit_price    NUMBER(12,2) NOT NULL,
  discount_rate NUMBER(4,2)  NOT NULL,
  line_total    NUMBER(14,2) NOT NULL,
  gross_amount  NUMBER(16,2) GENERATED ALWAYS AS (unit_price * quantity) VIRTUAL
);

CREATE TABLE events (
  id          NUMBER(10)     PRIMARY KEY,
  customer_id NUMBER(10)     NOT NULL REFERENCES customers (id),
  event_type  VARCHAR2(40)   NOT NULL,
  occurred_at TIMESTAMP      NOT NULL,
  session_id  VARCHAR2(40)   NOT NULL,
  device      VARCHAR2(40)   NOT NULL,
  duration_ms NUMBER(10)     NOT NULL,
  payload     VARCHAR2(4000) NOT NULL
);
`)
  // Oracle has no multi-row VALUES; INSERT ALL is the idiomatic bulk form.
  const oraTs = (v) => (v === null ? 'NULL' : `TO_TIMESTAMP(${sq(v)}, 'YYYY-MM-DD HH24:MI:SS')`)
  const oraDate = (v) => `TO_DATE(${sq(v)}, 'YYYY-MM-DD')`
  const insertAll = (table, columns, rows, toValues, batch = 50) => {
    const out = []
    for (let i = 0; i < rows.length; i += batch) {
      const chunk = rows.slice(i, i + batch)
      out.push('INSERT ALL\n' +
        chunk.map((r) => `  INTO ${table} (${columns.join(', ')}) VALUES (${toValues(r).join(', ')})`).join('\n') +
        '\nSELECT * FROM dual;')
    }
    return out.join('\n')
  }
  s.push(insertAll('customers',
    ['id', 'name', 'email', 'country_code', 'tier', 'credit_limit', 'is_active', 'signup_source', 'created_at', 'metadata'],
    data.customers,
    (c) => [num(c.id), sq(c.name), sq(c.email), sq(c.country_code), sq(c.tier),
      num(c.credit_limit), bool(c.is_active, 'int'), sq(c.signup_source), oraTs(c.created_at), json(c.metadata)]))
  s.push(insertAll('products',
    ['id', 'sku', 'name', 'category', 'price', 'weight_kg', 'in_stock', 'supplier', 'released_on', 'tags'],
    data.products,
    (p) => [num(p.id), sq(p.sku), sq(p.name), sq(p.category), num(p.price), num(p.weight_kg),
      bool(p.in_stock, 'int'), sq(p.supplier), oraDate(p.released_on), json(p.tags)]))
  s.push(insertAll('orders',
    ['id', 'customer_id', 'status', 'channel', 'currency', 'subtotal', 'tax', 'total', 'ordered_at', 'shipped_at', 'note'],
    data.orders,
    (o) => [num(o.id), num(o.customer_id), sq(o.status), sq(o.channel), sq(o.currency),
      num(o.subtotal), num(o.tax), num(o.total), oraTs(o.ordered_at), oraTs(o.shipped_at), sq(o.note)]))
  s.push(insertAll('order_items',
    ['id', 'order_id', 'product_id', 'quantity', 'unit_price', 'discount_rate', 'line_total'],
    data.orderItems,
    (i) => [num(i.id), num(i.order_id), num(i.product_id), num(i.quantity),
      num(i.unit_price), num(i.discount_rate), num(i.line_total)]))
  s.push(insertAll('events',
    ['id', 'customer_id', 'event_type', 'occurred_at', 'session_id', 'device', 'duration_ms', 'payload'],
    data.events,
    (e) => [num(e.id), num(e.customer_id), sq(e.event_type), oraTs(e.occurred_at), sq(e.session_id),
      sq(e.device), num(e.duration_ms), json(e.payload)]))
  s.push('\nCOMMIT;\nEXIT;\n')
  write('oracle/01_samples.sql', s.join('\n'))
}

// --- SQL Server -------------------------------------------------------------
{
  const s = [banner('SQL Server')]
  s.push(`
IF DB_ID('samples') IS NULL EXEC('CREATE DATABASE samples');
GO
USE samples;
GO
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO

DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS customers;
GO

CREATE TABLE customers (
  id            INT            NOT NULL PRIMARY KEY,
  name          NVARCHAR(200)  NOT NULL,
  email         NVARCHAR(200)  NOT NULL UNIQUE,
  country_code  CHAR(2)        NOT NULL,
  tier          VARCHAR(10)    NOT NULL,
  credit_limit  DECIMAL(14,2)  NOT NULL,
  is_active     BIT            NOT NULL,
  signup_source VARCHAR(40)    NOT NULL,
  created_at    DATETIME2(0)   NOT NULL,
  metadata      NVARCHAR(MAX)  NOT NULL
);

CREATE TABLE products (
  id          INT            NOT NULL PRIMARY KEY,
  sku         VARCHAR(32)    NOT NULL UNIQUE,
  name        NVARCHAR(200)  NOT NULL,
  category    VARCHAR(60)    NOT NULL,
  price       DECIMAL(12,2)  NOT NULL,
  weight_kg   DECIMAL(8,3)   NOT NULL,
  in_stock    BIT            NOT NULL,
  supplier    NVARCHAR(120)  NOT NULL,
  released_on DATE           NOT NULL,
  tags        NVARCHAR(MAX)  NOT NULL
);

CREATE TABLE orders (
  id          INT            NOT NULL PRIMARY KEY,
  customer_id INT            NOT NULL REFERENCES customers (id),
  status      VARCHAR(12)    NOT NULL,
  channel     VARCHAR(20)    NOT NULL,
  currency    CHAR(3)        NOT NULL,
  subtotal    DECIMAL(14,2)  NOT NULL,
  tax         DECIMAL(14,2)  NOT NULL,
  total       DECIMAL(14,2)  NOT NULL,
  ordered_at  DATETIME2(0)   NOT NULL,
  shipped_at  DATETIME2(0)   NULL,
  note        NVARCHAR(200)  NULL
);

CREATE TABLE order_items (
  id            INT           NOT NULL PRIMARY KEY,
  order_id      INT           NOT NULL REFERENCES orders (id),
  product_id    INT           NOT NULL REFERENCES products (id),
  quantity      INT           NOT NULL,
  unit_price    DECIMAL(12,2) NOT NULL,
  discount_rate DECIMAL(4,2)  NOT NULL,
  line_total    DECIMAL(14,2) NOT NULL,
  gross_amount  AS (unit_price * quantity) PERSISTED
);

CREATE TABLE events (
  id          INT           NOT NULL PRIMARY KEY,
  customer_id INT           NOT NULL REFERENCES customers (id),
  event_type  VARCHAR(40)   NOT NULL,
  occurred_at DATETIME2(0)  NOT NULL,
  session_id  VARCHAR(40)   NOT NULL,
  device      VARCHAR(40)   NOT NULL,
  duration_ms INT           NOT NULL,
  payload     NVARCHAR(MAX) NOT NULL
);
GO
`)
  // N'' literals so the Japanese/Korean/Arabic names survive without a UTF-8
  // collation on the database.
  const nq = (v) => (v === null || v === undefined ? 'NULL' : `N'${String(v).replaceAll("'", "''")}'`)
  s.push(inserts('customers',
    ['id', 'name', 'email', 'country_code', 'tier', 'credit_limit', 'is_active', 'signup_source', 'created_at', 'metadata'],
    data.customers,
    (c) => [num(c.id), nq(c.name), nq(c.email), sq(c.country_code), sq(c.tier),
      num(c.credit_limit), bool(c.is_active, 'int'), sq(c.signup_source), sq(c.created_at), nq(JSON.stringify(c.metadata))]))
  s.push(inserts('products',
    ['id', 'sku', 'name', 'category', 'price', 'weight_kg', 'in_stock', 'supplier', 'released_on', 'tags'],
    data.products,
    (p) => [num(p.id), sq(p.sku), nq(p.name), sq(p.category), num(p.price), num(p.weight_kg),
      bool(p.in_stock, 'int'), nq(p.supplier), sq(p.released_on), nq(JSON.stringify(p.tags))]))
  s.push(inserts('orders',
    ['id', 'customer_id', 'status', 'channel', 'currency', 'subtotal', 'tax', 'total', 'ordered_at', 'shipped_at', 'note'],
    data.orders,
    (o) => [num(o.id), num(o.customer_id), sq(o.status), sq(o.channel), sq(o.currency),
      num(o.subtotal), num(o.tax), num(o.total), sq(o.ordered_at), sq(o.shipped_at), nq(o.note)]))
  s.push(inserts('order_items',
    ['id', 'order_id', 'product_id', 'quantity', 'unit_price', 'discount_rate', 'line_total'],
    data.orderItems,
    (i) => [num(i.id), num(i.order_id), num(i.product_id), num(i.quantity),
      num(i.unit_price), num(i.discount_rate), num(i.line_total)]))
  s.push(inserts('events',
    ['id', 'customer_id', 'event_type', 'occurred_at', 'session_id', 'device', 'duration_ms', 'payload'],
    data.events,
    (e) => [num(e.id), num(e.customer_id), sq(e.event_type), sq(e.occurred_at), sq(e.session_id),
      sq(e.device), num(e.duration_ms), nq(JSON.stringify(e.payload))]))
  s.push('GO\n')
  write('sqlserver/01_samples.sql', s.join('\n'))
}

// --- ClickHouse -------------------------------------------------------------
{
  const s = [banner('ClickHouse')]
  s.push(`
CREATE DATABASE IF NOT EXISTS samples;

DROP TABLE IF EXISTS samples.events;
DROP TABLE IF EXISTS samples.order_items;
DROP TABLE IF EXISTS samples.orders;
DROP TABLE IF EXISTS samples.products;
DROP TABLE IF EXISTS samples.customers;

CREATE TABLE samples.customers (
  id UInt32, name String, email String,
  country_code LowCardinality(String),
  tier Enum8('bronze' = 1, 'silver' = 2, 'gold' = 3, 'platinum' = 4),
  credit_limit Decimal(14, 2), is_active Bool,
  signup_source LowCardinality(String), created_at DateTime, metadata String
) ENGINE = MergeTree ORDER BY id;

CREATE TABLE samples.products (
  id UInt32, sku String, name String, category LowCardinality(String),
  price Decimal(12, 2), weight_kg Decimal(8, 3), in_stock Bool,
  supplier LowCardinality(String), released_on Date, tags String
) ENGINE = MergeTree ORDER BY id;

CREATE TABLE samples.orders (
  id UInt32, customer_id UInt32, status LowCardinality(String),
  channel LowCardinality(String), currency LowCardinality(String),
  subtotal Decimal(14, 2), tax Decimal(14, 2), total Decimal(14, 2),
  ordered_at DateTime, shipped_at Nullable(DateTime), note Nullable(String)
) ENGINE = MergeTree ORDER BY (ordered_at, id);

CREATE TABLE samples.order_items (
  id UInt32, order_id UInt32, product_id UInt32, quantity UInt16,
  unit_price Decimal(12, 2), discount_rate Decimal(4, 2), line_total Decimal(14, 2)
) ENGINE = MergeTree ORDER BY (order_id, id);

CREATE TABLE samples.events (
  id UInt32, customer_id UInt32, event_type LowCardinality(String),
  occurred_at DateTime, session_id String, device LowCardinality(String),
  duration_ms UInt32, payload String
) ENGINE = MergeTree ORDER BY (occurred_at, customer_id);
`)
  s.push(inserts('samples.customers',
    ['id', 'name', 'email', 'country_code', 'tier', 'credit_limit', 'is_active', 'signup_source', 'created_at', 'metadata'],
    data.customers,
    (c) => [num(c.id), sq(c.name), sq(c.email), sq(c.country_code), sq(c.tier),
      num(c.credit_limit), bool(c.is_active), sq(c.signup_source), sq(c.created_at), json(c.metadata)]))
  s.push(inserts('samples.products',
    ['id', 'sku', 'name', 'category', 'price', 'weight_kg', 'in_stock', 'supplier', 'released_on', 'tags'],
    data.products,
    (p) => [num(p.id), sq(p.sku), sq(p.name), sq(p.category), num(p.price), num(p.weight_kg),
      bool(p.in_stock), sq(p.supplier), sq(p.released_on), json(p.tags)]))
  s.push(inserts('samples.orders',
    ['id', 'customer_id', 'status', 'channel', 'currency', 'subtotal', 'tax', 'total', 'ordered_at', 'shipped_at', 'note'],
    data.orders,
    (o) => [num(o.id), num(o.customer_id), sq(o.status), sq(o.channel), sq(o.currency),
      num(o.subtotal), num(o.tax), num(o.total), sq(o.ordered_at), sq(o.shipped_at), sq(o.note)]))
  s.push(inserts('samples.order_items',
    ['id', 'order_id', 'product_id', 'quantity', 'unit_price', 'discount_rate', 'line_total'],
    data.orderItems,
    (i) => [num(i.id), num(i.order_id), num(i.product_id), num(i.quantity),
      num(i.unit_price), num(i.discount_rate), num(i.line_total)]))
  s.push(inserts('samples.events',
    ['id', 'customer_id', 'event_type', 'occurred_at', 'session_id', 'device', 'duration_ms', 'payload'],
    data.events,
    (e) => [num(e.id), num(e.customer_id), sq(e.event_type), sq(e.occurred_at), sq(e.session_id),
      sq(e.device), num(e.duration_ms), json(e.payload)]))
  write('clickhouse/01_samples.sql', s.join('\n'))
}

// --- SQLite / DuckDB --------------------------------------------------------
// One file for both: the DDL below is the intersection they agree on, and both
// CLIs read it with `.read` / `<`.
{
  const s = [banner('SQLite and DuckDB')]
  s.push(`
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS customers;

CREATE TABLE customers (
  id INTEGER PRIMARY KEY, name VARCHAR NOT NULL, email VARCHAR NOT NULL UNIQUE,
  country_code VARCHAR NOT NULL, tier VARCHAR NOT NULL,
  credit_limit DECIMAL(14,2) NOT NULL, is_active BOOLEAN NOT NULL,
  signup_source VARCHAR NOT NULL, created_at TIMESTAMP NOT NULL, metadata VARCHAR NOT NULL
);
CREATE TABLE products (
  id INTEGER PRIMARY KEY, sku VARCHAR NOT NULL UNIQUE, name VARCHAR NOT NULL,
  category VARCHAR NOT NULL, price DECIMAL(12,2) NOT NULL, weight_kg DECIMAL(8,3) NOT NULL,
  in_stock BOOLEAN NOT NULL, supplier VARCHAR NOT NULL, released_on DATE NOT NULL, tags VARCHAR NOT NULL
);
CREATE TABLE orders (
  id INTEGER PRIMARY KEY, customer_id INTEGER NOT NULL REFERENCES customers (id),
  status VARCHAR NOT NULL, channel VARCHAR NOT NULL, currency VARCHAR NOT NULL,
  subtotal DECIMAL(14,2) NOT NULL, tax DECIMAL(14,2) NOT NULL, total DECIMAL(14,2) NOT NULL,
  ordered_at TIMESTAMP NOT NULL, shipped_at TIMESTAMP, note VARCHAR
);
CREATE TABLE order_items (
  id INTEGER PRIMARY KEY, order_id INTEGER NOT NULL REFERENCES orders (id),
  product_id INTEGER NOT NULL REFERENCES products (id), quantity INTEGER NOT NULL,
  unit_price DECIMAL(12,2) NOT NULL, discount_rate DECIMAL(4,2) NOT NULL, line_total DECIMAL(14,2) NOT NULL
);
CREATE TABLE events (
  id INTEGER PRIMARY KEY, customer_id INTEGER NOT NULL REFERENCES customers (id),
  event_type VARCHAR NOT NULL, occurred_at TIMESTAMP NOT NULL, session_id VARCHAR NOT NULL,
  device VARCHAR NOT NULL, duration_ms INTEGER NOT NULL, payload VARCHAR NOT NULL
);
`)
  s.push(inserts('customers',
    ['id', 'name', 'email', 'country_code', 'tier', 'credit_limit', 'is_active', 'signup_source', 'created_at', 'metadata'],
    data.customers,
    (c) => [num(c.id), sq(c.name), sq(c.email), sq(c.country_code), sq(c.tier),
      num(c.credit_limit), bool(c.is_active), sq(c.signup_source), sq(c.created_at), json(c.metadata)]))
  s.push(inserts('products',
    ['id', 'sku', 'name', 'category', 'price', 'weight_kg', 'in_stock', 'supplier', 'released_on', 'tags'],
    data.products,
    (p) => [num(p.id), sq(p.sku), sq(p.name), sq(p.category), num(p.price), num(p.weight_kg),
      bool(p.in_stock), sq(p.supplier), sq(p.released_on), json(p.tags)]))
  s.push(inserts('orders',
    ['id', 'customer_id', 'status', 'channel', 'currency', 'subtotal', 'tax', 'total', 'ordered_at', 'shipped_at', 'note'],
    data.orders,
    (o) => [num(o.id), num(o.customer_id), sq(o.status), sq(o.channel), sq(o.currency),
      num(o.subtotal), num(o.tax), num(o.total), sq(o.ordered_at), sq(o.shipped_at), sq(o.note)]))
  s.push(inserts('order_items',
    ['id', 'order_id', 'product_id', 'quantity', 'unit_price', 'discount_rate', 'line_total'],
    data.orderItems,
    (i) => [num(i.id), num(i.order_id), num(i.product_id), num(i.quantity),
      num(i.unit_price), num(i.discount_rate), num(i.line_total)]))
  s.push(inserts('events',
    ['id', 'customer_id', 'event_type', 'occurred_at', 'session_id', 'device', 'duration_ms', 'payload'],
    data.events,
    (e) => [num(e.id), num(e.customer_id), sq(e.event_type), sq(e.occurred_at), sq(e.session_id),
      sq(e.device), num(e.duration_ms), json(e.payload)]))
  write('sqlite/01_samples.sql', s.join('\n'))
  write('duckdb/01_samples.sql', s.join('\n'))
}

// --- Cassandra / ScyllaDB ---------------------------------------------------
{
  const s = [
    `-- Irodori Table sample data — Cassandra and ScyllaDB (CQL).`,
    `-- Generated by generator/generate.mjs (seed=${meta.SEED}, scale=${meta.SCALE}).`,
    `-- Do not edit by hand; re-run the generator instead.`,
    `--`,
    `-- CQL has no joins, so orders exist twice: once keyed by order id and once`,
    `-- clustered under the customer. That duplication is the model, not a mistake.`,
    `
CREATE KEYSPACE IF NOT EXISTS samples
  WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};
USE samples;

DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS orders_by_customer;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS customers;

CREATE TABLE customers (
  id int PRIMARY KEY, name text, email text, country_code text, tier text,
  credit_limit decimal, is_active boolean, signup_source text,
  created_at timestamp, metadata text
);
CREATE TABLE products (
  id int PRIMARY KEY, sku text, name text, category text, price decimal,
  weight_kg decimal, in_stock boolean, supplier text, released_on date, tags text
);
CREATE TABLE orders (
  id int PRIMARY KEY, customer_id int, status text, channel text, currency text,
  subtotal decimal, tax decimal, total decimal,
  ordered_at timestamp, shipped_at timestamp, note text
);
CREATE TABLE orders_by_customer (
  customer_id int, ordered_at timestamp, id int, status text, channel text,
  currency text, subtotal decimal, tax decimal, total decimal,
  shipped_at timestamp, note text,
  PRIMARY KEY ((customer_id), ordered_at, id)
) WITH CLUSTERING ORDER BY (ordered_at DESC, id ASC);
CREATE TABLE order_items (
  order_id int, id int, product_id int, quantity int,
  unit_price decimal, discount_rate decimal, line_total decimal,
  PRIMARY KEY ((order_id), id)
);
CREATE TABLE events (
  customer_id int, occurred_at timestamp, id int, event_type text,
  session_id text, device text, duration_ms int, payload text,
  PRIMARY KEY ((customer_id), occurred_at, id)
) WITH CLUSTERING ORDER BY (occurred_at DESC, id ASC);
`,
  ]
  // CQL has no multi-row VALUES; one INSERT per row, which is fine at this size.
  const cqlTs = (v) => (v === null ? 'null' : `'${v.replace(' ', 'T')}Z'`)
  const one = (table, columns, rows, toValues) =>
    rows.map((r) => `INSERT INTO ${table} (${columns.join(', ')}) VALUES (${toValues(r).join(', ')});`).join('\n')
  s.push(one('customers',
    ['id', 'name', 'email', 'country_code', 'tier', 'credit_limit', 'is_active', 'signup_source', 'created_at', 'metadata'],
    data.customers,
    (c) => [num(c.id), sq(c.name), sq(c.email), sq(c.country_code), sq(c.tier),
      num(c.credit_limit), String(c.is_active), sq(c.signup_source), cqlTs(c.created_at), json(c.metadata)]))
  s.push(one('products',
    ['id', 'sku', 'name', 'category', 'price', 'weight_kg', 'in_stock', 'supplier', 'released_on', 'tags'],
    data.products,
    (p) => [num(p.id), sq(p.sku), sq(p.name), sq(p.category), num(p.price), num(p.weight_kg),
      String(p.in_stock), sq(p.supplier), sq(p.released_on), json(p.tags)]))
  const orderCols = ['id', 'customer_id', 'status', 'channel', 'currency', 'subtotal', 'tax', 'total', 'ordered_at', 'shipped_at', 'note']
  const orderVals = (o) => [num(o.id), num(o.customer_id), sq(o.status), sq(o.channel), sq(o.currency),
    num(o.subtotal), num(o.tax), num(o.total), cqlTs(o.ordered_at), cqlTs(o.shipped_at), sq(o.note)]
  s.push(one('orders', orderCols, data.orders, orderVals))
  s.push(one('orders_by_customer', orderCols, data.orders, orderVals))
  s.push(one('order_items',
    ['id', 'order_id', 'product_id', 'quantity', 'unit_price', 'discount_rate', 'line_total'],
    data.orderItems,
    (i) => [num(i.id), num(i.order_id), num(i.product_id), num(i.quantity),
      num(i.unit_price), num(i.discount_rate), num(i.line_total)]))
  s.push(one('events',
    ['id', 'customer_id', 'event_type', 'occurred_at', 'session_id', 'device', 'duration_ms', 'payload'],
    data.events,
    (e) => [num(e.id), num(e.customer_id), sq(e.event_type), cqlTs(e.occurred_at), sq(e.session_id),
      sq(e.device), num(e.duration_ms), json(e.payload)]))
  write('cassandra/01_samples.cql', s.join('\n'))
}

// --- Neo4j / Memgraph -------------------------------------------------------
// No apostrophes anywhere in this file, including comments: mgconsole tracks
// quote state before stripping comments, and one stray ' swallows the rest of
// the file while still exiting 0.
{
  const s = [
    `// Irodori Table sample data -- Neo4j and Memgraph.`,
    `// Generated by generator/generate.mjs (seed=${meta.SEED}, scale=${meta.SCALE}).`,
    `// Do not edit by hand; re-run the generator instead.`,
    `//`,
    `// (:Customer)-[:PLACED]->(:Order)-[:CONTAINS]->(:Product)`,
    `// (:Customer)-[:TRIGGERED]->(:Event)`,
    `//`,
    `// No apostrophes in this file, comments included -- mgconsole would treat`,
    `// one as an unterminated string and silently skip everything after it.`,
    ``,
    `MATCH (n) DETACH DELETE n;`,
    ``,
  ]
  // Index syntax is the one place the two dialects part ways, so the body is
  // shared and only these lines differ. Neo4j 5 rejects the Memgraph form with
  // "Invalid create index syntax, use CREATE INDEX FOR ... instead".
  const INDEX_MARK = '@@INDEXES@@'
  const dt = (v) => (v === null ? 'null' : `datetime("${v.replace(' ', 'T')}")`)
  // UNWIND over a literal list, in chunks. One statement per row would be ~4,000
  // round trips through cypher-shell, which took over a minute; this is a few
  // dozen statements and finishes in seconds.
  const unwind = (rows, toProps, create, size = 200) => {
    const out = []
    for (let i = 0; i < rows.length; i += size) {
      out.push(`UNWIND [${rows.slice(i, i + size).map(toProps).join(', ')}] AS row\n${create};`)
    }
    return out.join('\n')
  }
  const props = (pairs) => '{' + pairs.map(([k, v]) => `${k}: ${v}`).join(', ') + '}'
  const str = (v) => (v === null ? 'null' : JSON.stringify(String(v)))

  s.push(unwind(data.customers,
    (c) => props([['id', c.id], ['name', str(c.name)], ['email', str(c.email)],
      ['country_code', str(c.country_code)], ['tier', str(c.tier)],
      ['credit_limit', c.credit_limit], ['is_active', c.is_active], ['created_at', dt(c.created_at)]]),
    'CREATE (:Customer {id: row.id, name: row.name, email: row.email, country_code: row.country_code, ' +
    'tier: row.tier, credit_limit: row.credit_limit, is_active: row.is_active, created_at: row.created_at})'))

  s.push(unwind(data.products,
    (p) => props([['id', p.id], ['sku', str(p.sku)], ['name', str(p.name)],
      ['category', str(p.category)], ['price', p.price], ['in_stock', p.in_stock],
      ['supplier', str(p.supplier)]]),
    'CREATE (:Product {id: row.id, sku: row.sku, name: row.name, category: row.category, ' +
    'price: row.price, in_stock: row.in_stock, supplier: row.supplier})'))

  s.push('')
  s.push('// Lookup indexes before the MATCH-heavy part. On Memgraph a uniqueness')
  s.push('// constraint is not a lookup index, so these are required, not optional.')
  s.push(INDEX_MARK)
  s.push('')

  s.push(unwind(data.orders,
    (o) => props([['id', o.id], ['customer_id', o.customer_id], ['status', str(o.status)],
      ['channel', str(o.channel)], ['currency', str(o.currency)], ['total', o.total],
      ['ordered_at', dt(o.ordered_at)]]),
    'MATCH (c:Customer {id: row.customer_id})\n' +
    'CREATE (c)-[:PLACED]->(:Order {id: row.id, status: row.status, channel: row.channel, ' +
    'currency: row.currency, total: row.total, ordered_at: row.ordered_at})'))

  s.push(unwind(data.orderItems,
    (i) => props([['order_id', i.order_id], ['product_id', i.product_id], ['quantity', i.quantity],
      ['unit_price', i.unit_price], ['line_total', i.line_total]]),
    'MATCH (o:Order {id: row.order_id}), (p:Product {id: row.product_id})\n' +
    'CREATE (o)-[:CONTAINS {quantity: row.quantity, unit_price: row.unit_price, line_total: row.line_total}]->(p)'))

  s.push(unwind(data.events,
    (e) => props([['id', e.id], ['customer_id', e.customer_id], ['event_type', str(e.event_type)],
      ['device', str(e.device)], ['duration_ms', e.duration_ms], ['occurred_at', dt(e.occurred_at)]]),
    'MATCH (c:Customer {id: row.customer_id})\n' +
    'CREATE (c)-[:TRIGGERED]->(:Event {id: row.id, event_type: row.event_type, device: row.device, ' +
    'duration_ms: row.duration_ms, occurred_at: row.occurred_at})'))

  const body = s.join('\n')
  write('neo4j/01_samples.cypher', body.replace(INDEX_MARK, [
    'CREATE INDEX customer_id IF NOT EXISTS FOR (c:Customer) ON (c.id);',
    'CREATE INDEX product_id  IF NOT EXISTS FOR (p:Product)  ON (p.id);',
    'CREATE INDEX order_id    IF NOT EXISTS FOR (o:Order)    ON (o.id);',
  ].join('\n')))
  write('memgraph/01_samples.cypher', body.replace(INDEX_MARK, [
    'CREATE INDEX ON :Customer(id);',
    'CREATE INDEX ON :Product(id);',
    'CREATE INDEX ON :Order(id);',
  ].join('\n')))
}

// --- Redis ------------------------------------------------------------------
// Plain commands, fed to redis-cli. Five data types so each renders differently.
{
  const s = [
    `# Irodori Table sample data — Redis.`,
    `# Generated by generator/generate.mjs (seed=${meta.SEED}, scale=${meta.SCALE}).`,
    `# Do not edit by hand; re-run the generator instead.`,
    `#`,
    `# Feed with: redis-cli --pipe < 01_samples.redis  (or -x per line)`,
    `FLUSHALL`,
  ]
  const esc = (v) => JSON.stringify(String(v))
  for (const c of data.customers) {
    s.push(`HSET customer:${c.id} name ${esc(c.name)} email ${esc(c.email)} country ${esc(c.country_code)} ` +
      `tier ${esc(c.tier)} credit_limit ${c.credit_limit} active ${c.is_active ? 1 : 0}`)
    s.push(`SADD customers:tier:${c.tier} ${c.id}`)
    s.push(`ZADD customers:by_credit ${c.credit_limit} customer:${c.id}`)
  }
  for (const p of data.products) {
    s.push(`HSET product:${p.id} sku ${esc(p.sku)} name ${esc(p.name)} category ${esc(p.category)} ` +
      `price ${p.price} in_stock ${p.in_stock ? 1 : 0}`)
  }
  for (const o of data.orders) {
    s.push(`HSET order:${o.id} customer_id ${o.customer_id} status ${esc(o.status)} ` +
      `currency ${esc(o.currency)} total ${o.total} ordered_at ${esc(o.ordered_at)}`)
    s.push(`LPUSH customer:${o.customer_id}:orders ${o.id}`)
  }
  for (const e of data.events) {
    s.push(`XADD events:stream * customer_id ${e.customer_id} type ${esc(e.event_type)} ` +
      `device ${esc(e.device)} duration_ms ${e.duration_ms}`)
  }
  s.push('SET config:app_name "Irodori Table samples"')
  s.push('SET config:locale "ja-JP"')
  write('redis/01_samples.redis', s.join('\n'))
}

console.log(`\n  ${data.customers.length} customers, ${data.products.length} products, ` +
  `${data.orders.length} orders, ${data.orderItems.length} order lines, ${data.events.length} events`)
console.log(`  ${data.customers.length + data.products.length + data.orders.length +
  data.orderItems.length + data.events.length} rows total`)
