use super::data::{Dataset, Order, OrderItem, iso_timestamp};
use super::{
    GeneratedFile, GeneratorConfig, json, json_sql, metadata_json, number, one_insert,
    payload_json, sql_quote,
};

pub(super) fn emit(data: &Dataset, config: GeneratorConfig) -> Vec<GeneratedFile> {
    let (neo4j, memgraph) = emit_graph(data, config);
    vec![
        GeneratedFile::new("mongodb/01_samples.js", emit_mongodb(data, config)),
        GeneratedFile::new("cassandra/01_samples.cql", emit_cassandra(data, config)),
        GeneratedFile::new("neo4j/01_samples.cypher", neo4j),
        GeneratedFile::new("memgraph/01_samples.cypher", memgraph),
        GeneratedFile::new("redis/01_samples.redis", emit_redis(data, config)),
    ]
}

fn emit_mongodb(data: &Dataset, config: GeneratorConfig) -> String {
    let mut sections = vec![
        "// Irodori Table sample data — MongoDB.".to_owned(),
        format!(
            "// Generated by task generate (seed={}, scale={}).",
            config.seed,
            number(config.scale)
        ),
        "// Do not edit by hand; re-run the generator instead.".to_owned(),
        "//".to_owned(),
        format!(
            "// order_items are embedded in orders, so this is {} order",
            data.orders.len()
        ),
        format!(
            "// documents holding {} lines between them.",
            data.order_items.len()
        ),
        "const db = db.getSiblingDB(\"samples\");".to_owned(),
        "db.customers.drop(); db.products.drop(); db.orders.drop(); db.events.drop();".to_owned(),
    ];
    sections.push(mongo_many("customers", &data.customers, |customer| {
        format!(
            "{{\"_id\":{},\"name\":{},\"email\":{},\"country_code\":{},\"tier\":{},\
             \"credit_limit\":{},\"is_active\":{},\"signup_source\":{},\"metadata\":{},\
             \"created_at\":ISODate(\"{}\")}}",
            customer.id,
            json(&customer.name),
            json(&customer.email),
            json(&customer.country_code),
            json(&customer.tier),
            number(customer.credit_limit),
            customer.is_active,
            json(&customer.signup_source),
            metadata_json(&customer.metadata),
            iso_timestamp(customer.created_ms)
        )
    }));
    sections.push(mongo_many("products", &data.products, |product| {
        format!(
            "{{\"_id\":{},\"sku\":{},\"name\":{},\"category\":{},\"price\":{},\
             \"weight_kg\":{},\"in_stock\":{},\"supplier\":{},\"released_on\":{},\"tags\":{}}}",
            product.id,
            json(&product.sku),
            json(&product.name),
            json(&product.category),
            number(product.price),
            number(product.weight_kg),
            product.in_stock,
            json(&product.supplier),
            json(&product.released_on),
            json(&product.tags)
        )
    }));
    sections.push(mongo_many("orders", &data.orders, mongo_order));
    sections.push(mongo_many("events", &data.events, |event| {
        format!(
            "{{\"_id\":{},\"customer_id\":{},\"event_type\":{},\"session_id\":{},\
             \"device\":{},\"duration_ms\":{},\"payload\":{},\"occurred_at\":ISODate(\"{}\")}}",
            event.id,
            event.customer_id,
            json(&event.event_type),
            json(&event.session_id),
            json(&event.device),
            event.duration_ms,
            payload_json(&event.payload),
            iso_timestamp(event.occurred_ms)
        )
    }));
    sections.push(
        r#"
db.customers.createIndex({ country_code: 1 });
db.customers.createIndex({ tier: 1, credit_limit: -1 });
db.products.createIndex({ sku: 1 }, { unique: true });
db.orders.createIndex({ customer_id: 1, ordered_at: -1 });
db.orders.createIndex({ "items.product_id": 1 });
db.events.createIndex({ customer_id: 1, occurred_at: -1 });
"#
        .to_owned(),
    );
    sections.join("\n")
}

fn mongo_many<T>(collection: &str, rows: &[T], document: impl Fn(&T) -> String) -> String {
    rows.chunks(100)
        .map(|chunk| {
            let documents = chunk
                .iter()
                .map(|row| format!("  {}", document(row)))
                .collect::<Vec<_>>()
                .join(",\n");
            format!("db.{collection}.insertMany([\n{documents}\n]);")
        })
        .collect::<Vec<_>>()
        .join("\n")
}

fn mongo_order(order: &Order) -> String {
    let items = order
        .items
        .iter()
        .map(|item| {
            format!(
                "{{\"product_id\":{},\"quantity\":{},\"unit_price\":{},\
                 \"discount_rate\":{},\"line_total\":{}}}",
                item.product_id,
                item.quantity,
                number(item.unit_price),
                number(item.discount_rate),
                number(item.line_total)
            )
        })
        .collect::<Vec<_>>()
        .join(",");
    let shipped_at = order.shipped_at.as_ref().map_or_else(
        || "null".to_owned(),
        |timestamp| format!("ISODate(\"{}.000Z\")", timestamp.replace(' ', "T")),
    );
    format!(
        "{{\"_id\":{},\"customer_id\":{},\"status\":{},\"channel\":{},\"currency\":{},\
         \"subtotal\":{},\"tax\":{},\"total\":{},\"note\":{},\"items\":[{}],\
         \"ordered_at\":ISODate(\"{}\"),\"shipped_at\":{}}}",
        order.id,
        order.customer_id,
        json(&order.status),
        json(&order.channel),
        json(&order.currency),
        number(order.subtotal),
        number(order.tax),
        number(order.total),
        json(&order.note),
        items,
        iso_timestamp(order.ordered_ms),
        shipped_at
    )
}

fn emit_cassandra(data: &Dataset, config: GeneratorConfig) -> String {
    let mut sections = vec![
        "-- Irodori Table sample data — Cassandra and ScyllaDB (CQL).".to_owned(),
        format!(
            "-- Generated by task generate (seed={}, scale={}).",
            config.seed,
            number(config.scale)
        ),
        "-- Do not edit by hand; re-run the generator instead.".to_owned(),
        "--".to_owned(),
        "-- CQL has no joins, so orders exist twice: once keyed by order id and once".to_owned(),
        "-- clustered under the customer. That duplication is the model, not a mistake.".to_owned(),
        CASSANDRA_SCHEMA.to_owned(),
    ];
    sections.push(one_insert(
        "customers",
        CUSTOMER_COLUMNS,
        &data.customers,
        |customer| {
            vec![
                customer.id.to_string(),
                sql_quote(Some(&customer.name)),
                sql_quote(Some(&customer.email)),
                sql_quote(Some(customer.country_code)),
                sql_quote(Some(customer.tier)),
                number(customer.credit_limit),
                customer.is_active.to_string(),
                sql_quote(Some(customer.signup_source)),
                cql_timestamp(Some(&customer.created_at)),
                sql_quote(Some(&metadata_json(&customer.metadata))),
            ]
        },
    ));
    sections.push(one_insert(
        "products",
        PRODUCT_COLUMNS,
        &data.products,
        |product| {
            vec![
                product.id.to_string(),
                sql_quote(Some(&product.sku)),
                sql_quote(Some(&product.name)),
                sql_quote(Some(product.category)),
                number(product.price),
                number(product.weight_kg),
                product.in_stock.to_string(),
                sql_quote(Some(product.supplier)),
                sql_quote(Some(&product.released_on)),
                json_sql(&product.tags),
            ]
        },
    ));
    sections.push(one_insert(
        "orders",
        ORDER_COLUMNS,
        &data.orders,
        cassandra_order_values,
    ));
    sections.push(one_insert(
        "orders_by_customer",
        ORDER_COLUMNS,
        &data.orders,
        cassandra_order_values,
    ));
    sections.push(one_insert(
        "order_items",
        ITEM_COLUMNS,
        &data.order_items,
        item_values,
    ));
    sections.push(one_insert("events", EVENT_COLUMNS, &data.events, |event| {
        vec![
            event.id.to_string(),
            event.customer_id.to_string(),
            sql_quote(Some(event.event_type)),
            cql_timestamp(Some(&event.occurred_at)),
            sql_quote(Some(&event.session_id)),
            sql_quote(Some(event.device)),
            event.duration_ms.to_string(),
            sql_quote(Some(&payload_json(&event.payload))),
        ]
    }));
    sections.join("\n")
}

fn cql_timestamp(value: Option<&str>) -> String {
    value.map_or_else(
        || "null".to_owned(),
        |value| format!("'{}Z'", value.replace(' ', "T")),
    )
}

fn cassandra_order_values(order: &Order) -> Vec<String> {
    vec![
        order.id.to_string(),
        order.customer_id.to_string(),
        sql_quote(Some(order.status)),
        sql_quote(Some(order.channel)),
        sql_quote(Some(order.currency)),
        number(order.subtotal),
        number(order.tax),
        number(order.total),
        cql_timestamp(Some(&order.ordered_at)),
        cql_timestamp(order.shipped_at.as_deref()),
        sql_quote(order.note),
    ]
}

fn item_values(item: &OrderItem) -> Vec<String> {
    vec![
        item.id.to_string(),
        item.order_id.to_string(),
        item.product_id.to_string(),
        item.quantity.to_string(),
        number(item.unit_price),
        number(item.discount_rate),
        number(item.line_total),
    ]
}

fn emit_graph(data: &Dataset, config: GeneratorConfig) -> (String, String) {
    const INDEX_MARK: &str = "@@INDEXES@@";
    let mut sections = vec![
        "// Irodori Table sample data -- Neo4j and Memgraph.".to_owned(),
        format!(
            "// Generated by task generate (seed={}, scale={}).",
            config.seed,
            number(config.scale)
        ),
        "// Do not edit by hand; re-run the generator instead.".to_owned(),
        "//".to_owned(),
        "// (:Customer)-[:PLACED]->(:Order)-[:CONTAINS]->(:Product)".to_owned(),
        "// (:Customer)-[:TRIGGERED]->(:Event)".to_owned(),
        "//".to_owned(),
        "// No apostrophes in this file, comments included -- mgconsole would treat".to_owned(),
        "// one as an unterminated string and silently skip everything after it.".to_owned(),
        String::new(),
        "MATCH (n) DETACH DELETE n;".to_owned(),
        String::new(),
    ];
    sections.push(unwind(
        &data.customers,
        |customer| {
            properties(&[
                ("id", customer.id.to_string()),
                ("name", json(&customer.name)),
                ("email", json(&customer.email)),
                ("country_code", json(&customer.country_code)),
                ("tier", json(&customer.tier)),
                ("credit_limit", number(customer.credit_limit)),
                ("is_active", customer.is_active.to_string()),
                ("created_at", graph_datetime(Some(&customer.created_at))),
            ])
        },
        "CREATE (:Customer {id: row.id, name: row.name, email: row.email, country_code: row.country_code, tier: row.tier, credit_limit: row.credit_limit, is_active: row.is_active, created_at: row.created_at})",
    ));
    sections.push(unwind(
        &data.products,
        |product| {
            properties(&[
                ("id", product.id.to_string()),
                ("sku", json(&product.sku)),
                ("name", json(&product.name)),
                ("category", json(&product.category)),
                ("price", number(product.price)),
                ("in_stock", product.in_stock.to_string()),
                ("supplier", json(&product.supplier)),
            ])
        },
        "CREATE (:Product {id: row.id, sku: row.sku, name: row.name, category: row.category, price: row.price, in_stock: row.in_stock, supplier: row.supplier})",
    ));
    sections.push(String::new());
    sections
        .push("// Lookup indexes before the MATCH-heavy part. On Memgraph a uniqueness".to_owned());
    sections.push(
        "// constraint is not a lookup index, so these are required, not optional.".to_owned(),
    );
    sections.push(INDEX_MARK.to_owned());
    sections.push(String::new());
    sections.push(unwind(
        &data.orders,
        |order| {
            properties(&[
                ("id", order.id.to_string()),
                ("customer_id", order.customer_id.to_string()),
                ("status", json(&order.status)),
                ("channel", json(&order.channel)),
                ("currency", json(&order.currency)),
                ("total", number(order.total)),
                ("ordered_at", graph_datetime(Some(&order.ordered_at))),
            ])
        },
        "MATCH (c:Customer {id: row.customer_id})\nCREATE (c)-[:PLACED]->(:Order {id: row.id, status: row.status, channel: row.channel, currency: row.currency, total: row.total, ordered_at: row.ordered_at})",
    ));
    sections.push(unwind(
        &data.order_items,
        |item| {
            properties(&[
                ("order_id", item.order_id.to_string()),
                ("product_id", item.product_id.to_string()),
                ("quantity", item.quantity.to_string()),
                ("unit_price", number(item.unit_price)),
                ("line_total", number(item.line_total)),
            ])
        },
        "MATCH (o:Order {id: row.order_id}), (p:Product {id: row.product_id})\nCREATE (o)-[:CONTAINS {quantity: row.quantity, unit_price: row.unit_price, line_total: row.line_total}]->(p)",
    ));
    sections.push(unwind(
        &data.events,
        |event| {
            properties(&[
                ("id", event.id.to_string()),
                ("customer_id", event.customer_id.to_string()),
                ("event_type", json(&event.event_type)),
                ("device", json(&event.device)),
                ("duration_ms", event.duration_ms.to_string()),
                ("occurred_at", graph_datetime(Some(&event.occurred_at))),
            ])
        },
        "MATCH (c:Customer {id: row.customer_id})\nCREATE (c)-[:TRIGGERED]->(:Event {id: row.id, event_type: row.event_type, device: row.device, duration_ms: row.duration_ms, occurred_at: row.occurred_at})",
    ));

    let body = sections.join("\n");
    (
        body.replace(
            INDEX_MARK,
            "CREATE INDEX customer_id IF NOT EXISTS FOR (c:Customer) ON (c.id);\n\
             CREATE INDEX product_id  IF NOT EXISTS FOR (p:Product)  ON (p.id);\n\
             CREATE INDEX order_id    IF NOT EXISTS FOR (o:Order)    ON (o.id);",
        ),
        body.replace(
            INDEX_MARK,
            "CREATE INDEX ON :Customer(id);\n\
             CREATE INDEX ON :Product(id);\n\
             CREATE INDEX ON :Order(id);",
        ),
    )
}

fn graph_datetime(value: Option<&str>) -> String {
    value.map_or_else(
        || "null".to_owned(),
        |value| format!("datetime(\"{}\")", value.replace(' ', "T")),
    )
}

fn properties(values: &[(&str, String)]) -> String {
    format!(
        "{{{}}}",
        values
            .iter()
            .map(|(key, value)| format!("{key}: {value}"))
            .collect::<Vec<_>>()
            .join(", ")
    )
}

fn unwind<T>(rows: &[T], properties: impl Fn(&T) -> String, create: &str) -> String {
    rows.chunks(200)
        .map(|chunk| {
            let rows = chunk.iter().map(&properties).collect::<Vec<_>>().join(", ");
            format!("UNWIND [{rows}] AS row\n{create};")
        })
        .collect::<Vec<_>>()
        .join("\n")
}

fn emit_redis(data: &Dataset, config: GeneratorConfig) -> String {
    let mut lines = vec![
        "# Irodori Table sample data — Redis.".to_owned(),
        format!(
            "# Generated by task generate (seed={}, scale={}).",
            config.seed,
            number(config.scale)
        ),
        "# Do not edit by hand; re-run the generator instead.".to_owned(),
        "#".to_owned(),
        "# Feed with: redis-cli --pipe < 01_samples.redis  (or -x per line)".to_owned(),
        "FLUSHALL".to_owned(),
    ];
    for customer in &data.customers {
        lines.push(format!(
            "HSET customer:{} name {} email {} country {} tier {} credit_limit {} active {}",
            customer.id,
            json(&customer.name),
            json(&customer.email),
            json(&customer.country_code),
            json(&customer.tier),
            number(customer.credit_limit),
            u8::from(customer.is_active)
        ));
        lines.push(format!(
            "SADD customers:tier:{} {}",
            customer.tier, customer.id
        ));
        lines.push(format!(
            "ZADD customers:by_credit {} customer:{}",
            number(customer.credit_limit),
            customer.id
        ));
    }
    for product in &data.products {
        lines.push(format!(
            "HSET product:{} sku {} name {} category {} price {} in_stock {}",
            product.id,
            json(&product.sku),
            json(&product.name),
            json(&product.category),
            number(product.price),
            u8::from(product.in_stock)
        ));
    }
    for order in &data.orders {
        lines.push(format!(
            "HSET order:{} customer_id {} status {} currency {} total {} ordered_at {}",
            order.id,
            order.customer_id,
            json(&order.status),
            json(&order.currency),
            number(order.total),
            json(&order.ordered_at)
        ));
        lines.push(format!(
            "LPUSH customer:{}:orders {}",
            order.customer_id, order.id
        ));
    }
    for event in &data.events {
        lines.push(format!(
            "XADD events:stream * customer_id {} type {} device {} duration_ms {}",
            event.customer_id,
            json(&event.event_type),
            json(&event.device),
            event.duration_ms
        ));
    }
    lines.push("SET config:app_name \"Irodori Table samples\"".to_owned());
    lines.push("SET config:locale \"ja-JP\"".to_owned());
    lines.join("\n")
}

const CUSTOMER_COLUMNS: &[&str] = &[
    "id",
    "name",
    "email",
    "country_code",
    "tier",
    "credit_limit",
    "is_active",
    "signup_source",
    "created_at",
    "metadata",
];
const PRODUCT_COLUMNS: &[&str] = &[
    "id",
    "sku",
    "name",
    "category",
    "price",
    "weight_kg",
    "in_stock",
    "supplier",
    "released_on",
    "tags",
];
const ORDER_COLUMNS: &[&str] = &[
    "id",
    "customer_id",
    "status",
    "channel",
    "currency",
    "subtotal",
    "tax",
    "total",
    "ordered_at",
    "shipped_at",
    "note",
];
const ITEM_COLUMNS: &[&str] = &[
    "id",
    "order_id",
    "product_id",
    "quantity",
    "unit_price",
    "discount_rate",
    "line_total",
];
const EVENT_COLUMNS: &[&str] = &[
    "id",
    "customer_id",
    "event_type",
    "occurred_at",
    "session_id",
    "device",
    "duration_ms",
    "payload",
];

const CASSANDRA_SCHEMA: &str = r#"
CREATE KEYSPACE IF NOT EXISTS samples
  WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};
USE samples;

DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS orders_by_customer;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS customers;

CREATE TABLE customers (
  id int PRIMARY KEY, name text, email text, country_code text, tier text,
  credit_limit decimal, is_active boolean, signup_source text,
  created_at timestamp, metadata text
);
CREATE TABLE products (
  id int PRIMARY KEY, sku text, name text, category text, price decimal,
  weight_kg decimal, in_stock boolean, supplier text, released_on date, tags text
);
CREATE TABLE orders (
  id int PRIMARY KEY, customer_id int, status text, channel text, currency text,
  subtotal decimal, tax decimal, total decimal,
  ordered_at timestamp, shipped_at timestamp, note text
);
CREATE TABLE orders_by_customer (
  customer_id int, ordered_at timestamp, id int, status text, channel text,
  currency text, subtotal decimal, tax decimal, total decimal,
  shipped_at timestamp, note text,
  PRIMARY KEY ((customer_id), ordered_at, id)
) WITH CLUSTERING ORDER BY (ordered_at DESC, id ASC);
CREATE TABLE order_items (
  order_id int, id int, product_id int, quantity int,
  unit_price decimal, discount_rate decimal, line_total decimal,
  PRIMARY KEY ((order_id), id)
);
CREATE TABLE events (
  customer_id int, occurred_at timestamp, id int, event_type text,
  session_id text, device text, duration_ms int, payload text,
  PRIMARY KEY ((customer_id), occurred_at, id)
) WITH CLUSTERING ORDER BY (occurred_at DESC, id ASC);
"#;
